# Generated by Django 6.0.7 on 2026-07-21 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 's',
            },
        ),
    ]
