# Generated by Django 6.0.7 on 2026-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_active_user_activate_remove_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'cliente'), ('BARBEIRO', 'barbeiro')], default='CLIENTE', max_length=200),
        ),
    ]
