# Generated by Django 6.0.7 on 2026-08-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENTE', 'cliente'), ('BARBEIRO', 'barbeiro'), ('ADMIN', 'admin')], max_length=200),
        ),
    ]
