# Generated by Django 6.0.7 on 2026-07-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='usuario_id',
            new_name='user_id',
        ),
    ]
