# Generated by Django 6.0.7 on 2026-08-14 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
