# Generated by Django 6.0.7 on 2026-09-15 23:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('AGENDODO', 'agendado'), ('CANCELADO', 'cancelado'), ('FALTOU', 'faltou'), ('CONCLUIDO', 'concluido')], default='AGENDODO', max_length=30)),
                ('observation', models.TextField()),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
