# Generated by Django 6.0.7 on 2026-09-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barber'),
        ),
    ]
