# Generated by Django 6.0.7 on 2026-09-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
