# Generated by Django 6.0.7 on 2026-09-07 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_delete_appointments'),
        ('barber', '0004_alter_barber_activate'),
        ('clients', '0003_rename_user_id_client_user'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'agendado'), ('CANCELADO', 'cancelado'), ('FALTOU', 'faltou'), ('CONCLUIDO', 'concluido')], default='AGENDADO', max_length=100)),
                ('observation', models.TextField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barber')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
