# Generated by Django 6.0.7 on 2026-08-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='activate',
            field=models.IntegerField(default=0),
        ),
    ]
