# Generated by Django 6.0.7 on 2026-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_alter_barber_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
