# Generated by Django 6.0.7 on 2026-08-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_alter_barber_activate_alter_barber_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
