# Generated by Django 6.0.7 on 2026-09-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumerservice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumerService',
        ),
    ]
