# Generated by Django 6.0.7 on 2026-09-20 02:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_initial'),
        ('barber', '0001_initial'),
        ('clients', '0001_initial'),
        ('costumerservice', '0004_delete_costumerservice'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('deduct', models.FloatField()),
                ('total_value', models.FloatField()),
                ('end_value', models.FloatField()),
                ('observation', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.barber')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
            options={
                'db_table': 'ConstumerService',
            },
        ),
    ]
