# Generated by Django 6.0.7 on 2026-09-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumerservice', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumerservice',
            name='end_value',
            field=models.FloatField(default=0),
        ),
    ]
